### ISSUE TITLE
这个报错不知道为什么qwq 求解惑

### ISSUE THREAD

**Issue by h3rrr** [simple-robot/simbot-mirai-demo#3]
| love.simbot.example.SimbotExampleApplication : Active resources: [simbot.yml]
Exception in thread "main" love.forte.common.ioc.exception.NoSuchDependException: interface love.forte.simbot.bot.BotManager
        at love.forte.common.ioc.DependCenter.get(DependCenter.kt:945)
        at love.forte.simbot.core.SimbotApp.createSimbotContext(SimbotApp.kt:411)
        at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:250)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:471)
        at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:434)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
        at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
        at love.simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:36)

运行之后就爆错这个

**Comment by ForteScarlet** [comment]
是否对代码做了修改？
如果是，提供修改的内容；
如果不是，提供完整日志：从启动到报错的全部 **debug** 日志

**Comment by h3rrr** [comment]
ubuntu@VM-4-6-ubuntu:~$ java -jar simbot-mirai-demo.jar

     _           _           _
    (_)         | |         | |
 ___ _ _ __ ___ | |__   ___ | |_
/ __| | '_ ` _ \| '_ \ / _ \| __|
\__ \ | | | | | | |_) | (_) | |_
|___/_|_| |_| |_|_.__/ \___/ \__|
                 @ForteScarlet  D


Tips: 你知道吗？simbot开发团队一直希望拥有一个活跃的社区。因此它们将文档的团队讨论区定义为社区，并期待着人们的讨论。

[2021-08-08T22:51:38.484201]-[INFO ] | love.simbot.example.SimbotExampleApplication : Active resources: [simbot.yml]
Exception in thread "main" love.forte.common.ioc.exception.NoSuchDependException: interface love.forte.simbot.bot.BotManager
        at love.forte.common.ioc.DependCenter.get(DependCenter.kt:945)
        at love.forte.simbot.core.SimbotApp.createSimbotContext(SimbotApp.kt:411)
        at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:250)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:471)
        at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:434)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
        at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
        at love.simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:36)

没有对代码进行修改除了我写的部分以外，其他部分没有改变

**Comment by ForteScarlet** [comment]
不打包，直接通过IDE启动会出现错误吗？如果不会，参考文档 [打包](https://www.yuque.com/simpler-robot/simpler-robot-doc/lgm0w3)

**Comment by h3rrr** [comment]
不打包的话启动是没有问题的，但是关于打包这一步我不是特别能看懂qwq，我将打包的内容放在了pom.xml之后一直出现报错
![M17C}M10KJA02S ~PCUD22V](https://user-images.githubusercontent.com/81402797/128637457-98bb9297-85cd-4e84-939d-72b20356c06e.png)

**Comment by h3rrr** [comment]
请问一下大大 这个怎么解决呀qwq  麻烦大大了

**Comment by ForteScarlet** [comment]
```xml
<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <!-- main方法所在类。 -->
                    <mainClass>simbot.example.SimbotExampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

其中 `<mainClass>simbot.example.SimbotExampleApplication</mainClass>` 的内容替换为你的`main`方法所在类的全限定路径，然后使用 `mvn package` 命令或者idea右侧maven工具栏中 `Lifecycle -> package` 进行打包

**Comment by h3rrr** [comment]
为什么我无论将这一段放在哪 都会出现报错呢呜呜

**Comment by ForteScarlet** [comment]
https://github.com/simple-robot/simbot-mirai-demo/blob/master/pom.xml

**Comment by h3rrr** [comment]
对不起对不起大大 我真的不知道为什么报错qwq 我按照你给的样式放上去 结果还是出现了报错 对不起对不起 又要麻烦你了qwq555
![274XT_Q)GAFK2HXNXYETG5J](https://user-images.githubusercontent.com/81402797/128637915-dfc9bf98-98de-45a9-89ce-a0b2b05ea649.png)

**Comment by h3rrr** [comment]
![ZAX ~$~_9M`ATX`ZP%_T6U9](https://user-images.githubusercontent.com/81402797/128638061-7e986b89-2689-4bad-b914-8dd8a7d9ddc1.png)
报错是这样的

**Comment by ForteScarlet** [comment]
提供完整的pom文件内容

**Comment by h3rrr** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <parent>
        <groupId>love.forte.simple-robot</groupId>
        <artifactId>parent</artifactId>
        <version>2.1.1</version>
    </parent>

    <groupId>simbot.example</groupId>
    <artifactId>simbot-mirai-demo</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>love.forte.simple-robot</groupId>
            <artifactId>component-mirai</artifactId>
        </dependency>


        
        <dependency>
            <groupId>love.forte.simple-robot.time-task</groupId>
            <artifactId>time-task-quartz</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.8</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.3</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.11</version>
            <scope>test</scope>
        </dependency>

        
        <dependency>
            <groupId>link.zhangfei</groupId>
            <artifactId>zson</artifactId>
            <version>1.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.8.1</version>
        </dependency>

        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>3.6.1</version>
        </dependency>

        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>3.3.0</version>
            <type>jar</type>
            <scope>compile</scope>
        </dependency>

        
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.15</version>
        </dependency>
    </dependencies>

    

</project>

**Comment by h3rrr** [comment]
这是没有添加大大给我的那一段的时候的pom

**Comment by ForteScarlet** [comment]
你在最上面有一个 `build` 标签了。

**Comment by h3rrr** [comment]
那我这个是需要怎么添加进去呢qwq Java小白

**Comment by ForteScarlet** [comment]
`build - plugins` 里面不是有 `plugin` 标签吗，把所有plugin标签都放在 `build - plugins` 里

**Comment by h3rrr** [comment]
谢谢大大，我成功的在pom里添加了 但是在服务器上运行的时候还是报错了qwq，一样的报错
![LSN 59QV({%2X50X9U2TFY8](https://user-images.githubusercontent.com/81402797/128638559-f78afa69-494a-4616-aba9-73309b5dd30b.png)

**Comment by ForteScarlet** [comment]
是通过maven打包的吗

**Comment by h3rrr** [comment]
是直接通过IDEA里面的这个打包的 
![%ZK03{X@0K9OWDZ3JXW{IH7](https://user-images.githubusercontent.com/81402797/128638635-1ac87a76-3759-4534-912d-45de618e9653.png)

**Comment by ForteScarlet** [comment]
> ```
> <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>                 <version>2.5.3</version>
>                 <configuration>
>                     
>                     <mainClass>simbot.example.SimbotExampleApplication</mainClass>
>                 </configuration>
>                 <executions>
>                     <execution>
>                         <goals>
>                             <goal>repackage</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
>         </plugins>
>     </build>
> ```
> 
> 其中 `<mainClass>simbot.example.SimbotExampleApplication</mainClass>` 的内容替换为你的`main`方法所在类的全限定路径，然后使用 `mvn package` 命令或者idea右侧maven工具栏中 `Lifecycle -> package` 进行打包

我上面说了，用maven打包

**Comment by h3rrr** [comment]
啊啊啊 对不起对不起 我没有注意到 我从新试一下

**Comment by h3rrr** [comment]
qwq 谢谢谢谢大大 真的谢谢大大 成功了 大大早点睡觉呀！！！
